backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "blogs"
    label: "Blogs"
    folder: "blogs"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
